FROM python:3.12.3

WORKDIR /app

ARG PORT
ENV PORT=${PORT:-3001}

# Copy requirements file and install dependencies
COPY app/service/requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy your application code
COPY app/service/src /app/src
COPY app/service/entrypoint.sh /app/entrypoint.sh

EXPOSE ${PORT}

CMD ["/bin/bash", "/app/entrypoint.sh"]
